### ISSUE TITLE
Ranger Admin/KMS install needs "python2" for Rocky/Alma 8

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection-prerequisites#20]
See https://github.com/TOSIT-IO/tdp-collection/issues/419.

**Comment by rpignolet** [comment]
@gboutry @leopaul36 Do we install `bc` and `python2` on all hosts or just for `ranger_admin` and `ranger_kms` group ? I think we should install `python2` only for Ranger which have script not compatible with `python3`.

**Comment by leopaul36** [comment]
I think Spark 2 runs on Python 2 so we might also need it on the edge and workers right @Nuttymoon?

With this in mind we might as well install it everywhere?

**Comment by rpignolet** [comment]
PySpark 2 can run on Python 3, we configure it on HDP 3.1.4 at DGFiP but I don't know if it's working well.

**Comment by gboutry** [comment]
It looks like PySpark 2.3 is compatible python 3.6, I think we would just need to adapt scripts on spark installation to run with python3 instead.

**Comment by leopaul36** [comment]
I think it's best to keep both Python 2 and 3 and let the users run what they want for compatibility issues when moving from CDH / HDP to TDP for instance

**Comment by Nuttymoon** [comment]
From what I have seen, Ranger can go around not having `bc` installed (sometimes there are errors complaining about `bc` but they are not fatal).

For Spark I agree with Léo that we should let users select their Python version.

**Comment by rpignolet** [comment]
Ok I will try without `bc`.

For `python2` ok to install it on all hosts for Rocky 8 and above. Centos 7 already have python2 installed.

**Comment by rpignolet** [comment]
Python 2 is not available in Redhat 9 https://access.redhat.com/solutions/4455511. So Rocky 9 and Alma 9 is not supported. I will remove it from the list. It is maybe too early to try to support them.
