### ISSUE TITLE
PostgreSQL: public repo installation fails because of non trusted SSL certificate 

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection-prerequisites#26]
When `postgresql_use_public_repo: yes`, the PostgreSQL role fails with:

```
TASK [tosit.tdp_prerequisites.postgresql : Install PostgreSQL public repo RPM] ***************************
fatal: [master-03]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  msg: 'Failure downloading https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>'
```

Using the option `validate_certs: no` fixes the issue.

**Comment by rpignolet** [comment]
You should use an OS up to date or update `ca-certificates` package. What OS do you use ? The vagrant box `centos/7` ?

**Comment by Nuttymoon** [comment]
I am using the `centos/7` box. Updating `ca-certificates` solves the issue.

**Comment by rpignolet** [comment]
This PR https://github.com/TOSIT-IO/tdp-vagrant/pull/19 change Vagrant box from `centos/7` to `generic/centos7` which is a newer image.
