### ISSUE TITLE
Hive (metastore) uses ```public``` Postgres schema to store SQL tables

### ISSUE THREAD

**Issue by kpgtek** [TOSIT-IO/tdp-collection-prerequisites#28]
According to the script SQL ```hive-schema-3.1.0.postgres.sql``` used by ```hive``` to initiate schema in Postgres database, it seems that ```hive``` forces to use the ```public``` schema to create SQL tables, this is hard coded in the script, line 12:

```SET search_path = public, pg_catalog;```

Thus in ```postgresql``` role, there will not need to create a SQL schema in ```hive``` database.

**Comment by kpgtek** [comment]
Note: use ```public``` schema for an application is not best practice in PostgreSQL ([Database Schema Recommendations](https://wiki.postgresql.org/wiki/Database_Schema_Recommendations_for_an_Application)).

**Comment by rpignolet** [comment]
As discuss today, disable schema generation for Hive to avoid modify Hive code.
