### ISSUE TITLE
authselect current might not be defined

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection-prerequisites#34]
If `authselect` was not configured before `tdp_prerequisites` deployment, `authselect current` returns an error: `No existing configuration detected`.

We should support this case.

**Comment by rpignolet** [comment]
How it is possible ? In Redhat 8 the default auth is `sssd`. (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_authentication_and_authorization_in_rhel/index#configuring-user-authentication-using-authselect_configuring-authentication-and-authorization-in-rhel)

**Comment by Nuttymoon** [comment]
> How it is possible ? In Redhat 8 the default auth is `sssd`. (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_authentication_and_authorization_in_rhel/index#configuring-user-authentication-using-authselect_configuring-authentication-and-authorization-in-rhel)

The `authselect` package is not included in LXD Rocky 8 image. When installing the package, it has no configuration.
