### ISSUE TITLE
Add netcat to the list of default_packages

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection-prerequisites#39]
We should add netcat to the list of packages to install with `default_packages` since it is used in many service checks.

**Comment by rpignolet** [comment]
Netcat is installed with `nc` package which is installed

https://github.com/TOSIT-IO/tdp-collection-prerequisites/blob/55cda26dd6788203f6e9a56a1ae3c39f71d016e9/roles/system/defaults/main.yml#L21
