### ISSUE TITLE
Add Fluentbit installation + configuration

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection-prerequisites#62]
We should be able to install and configure Fluentbit with `tdp-collection-prerequisites` in order to use the sample Fluentbit configuration files to tail the logs of the TDP services we will implement in `tdp-collection` with https://github.com/TOSIT-IO/tdp-collection/issues/613

**Comment by rpignolet** [comment]
Closing in favor of https://github.com/TOSIT-IO/tdp-observability/pull/24
