### ISSUE TITLE
"Error loading psycopg2 module" when using python2-psycopg2 on CentOS 7

### ISSUE THREAD

**Issue by kpgtek** [TOSIT-IO/tdp-collection-prerequisites#64]
On CentOS 7, after installing the package ```python2-psycopg2``` for PostgreSQL packages client, when trying to connect from a client to PostgreSQL server through the ```psycopg2``` module, we got the following error message:
```
Error loading psycopg2 module: /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PQconninfo
```

**Comment by leopaul36** [comment]
I also had this issue which was resolved by installing `psycopg2-binary`. I don't think there is a RPM package for this one...
