### ISSUE TITLE
Should topology.ini reference hadoop components ?

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-collection-prerequisites#67]
In the topology.ini files the section [postgresql_client:children] references tdp-collection and tdp-collection-extras host groups:

```ini
(...)
[postgresql_client:children]
ranger_admin
ranger_kms
hive_ms
hue_server
```

It causes issues if one would install hadoop (in tdp-collection) without hue (in tdp-extras) for example.The issues are a lot of warning during a deployment.

They are simply due to hue_server being referenced in this file, but no section [hue_server:children] could be found (included in the topology.ini of the tdp-collection-extras file).

The issue can be resolved if the section [postgresql_client:children] were to be included in the topology.ini of the appropriate repository. E.G:

```ini
# tdp_collection's topology.ini
[postgresql_client:children]
ranger_admin
ranger_kms
hive_ms
```
```ini
# tdp_extra's topology.ini
[postgresql_client:children]
hue_server
```

The two files are merged without issues by Ansible.

**Comment by rpignolet** [comment]
Ok for me since Ansible does the merge in the case of multiple definition of the same group.
